package Exception;

public class tryCatch3 {
public static void main(String[] args) {
	

	int a = 12;
	int b= 0;
	int c = 0;
	int e = 0;
	int d[] = {1,2,3,4};
	
	
	try {
		 
		
			 c = a/b;
			
		 
		 
	}

  
	catch(ArithmeticException z){
		   System.out.println("ArithmeticException");
		 
	 }
	  b=5;
	   //c= a/b;
	   System.out.println("catch 1= "+c);
	   
		   
	   
		  
	   }
	   
       
}
